#!/usr/bin/env python
"""
regen.py — rebuild cache/ by running its producers.

cache/ is the workshop — rebuildable derivations. Its producer commands are
DECLARED in rsc/cache_io.csv (written_by); regen runs the distinct set, in
first-declared order. Paired with clean, this is the reproduction the cache/
contract promises: `yoga clean --apply && yoga regen` gives a fresh cache/ from
input/ + output/ alone.

Producers are only ever FREE, local derivations — the paid `yoga dashboard
capture` is not among them (cache/dashboard is regenerated by `present`, which
reads the already-captured output/dashboard). regen never spends money and never
writes output/.

STDLIB-ONLY.

Usage:
    ./yoga regen             # run every producer
    ./yoga regen --dry-run   # print the producer commands; run nothing
"""
import argparse
import subprocess
import sys
from pathlib import Path

from cache_io import producers

REPO = Path(__file__).resolve().parents[3]


def main() -> int:
    ap = argparse.ArgumentParser(description='rebuild cache/ by running its declared producers')
    ap.add_argument('--dry-run', action='store_true', help='print the producer commands; run nothing')
    args = ap.parse_args()

    cmds = producers()
    if args.dry_run:
        print(f'regen plan — {len(cmds)} producer(s), in order:')
        for c in cmds:
            print(f'    → run: {c}')
        print('DONE — dry run: pass no flag to execute')
        return 0

    failures = []
    for c in cmds:
        print(f'── regen: {c} ───────────────────────────────')
        rc = subprocess.run(c, shell=True, cwd=REPO).returncode
        if rc != 0:
            failures.append((c, rc))
        print()

    if failures:
        print(f'DONE — {len(cmds)} producer(s) run, {len(failures)} FAILED:')
        for c, rc in failures:
            print(f'  FAIL: {c} (exit {rc})')
        return 1
    print(f'DONE — {len(cmds)} producer(s) run, cache/ rebuilt')
    return 0


if __name__ == '__main__':
    sys.exit(main())
