#!/usr/bin/env python
"""
sync.py — rebuild tmp/cache/ by running its producers.

tmp/cache/ is the workshop — rebuildable derivations. Its producer commands are
DECLARED in rsc/cache_io.csv (written_by); sync runs every row's producers,
in registry-row order (no dedup — the row is the unit of the claim). Paired with clean, this is the reproduction the tmp/cache/
contract promises: `yoga cache clean --apply && yoga cache sync` gives a fresh tmp/cache/ from
data/input/ + data/output/ alone — plus, for the one fetched subtree, the pinned CDN it
declares: `yoga server ensure-assets` fetches tmp/cache/serve_markdown's render
libraries (KaTeX + marked), which live nowhere local. That producer is best-effort
(it warns and exits clean if offline; serve re-fetches at startup), so an offline
sync still rebuilds every other subtree.

Producers are FREE and — but for that render-asset fetch — LOCAL. The paid `yoga
dashboard capture` is not among them (tmp/cache/dashboard is regenerated by `present`,
which reads the already-captured data/output/dashboard). sync never spends money. It
DOES co-write data/output/: the pipeline producers project markdown there, and
`dashboard sync` lands the corpus page in data/output/dashboard/presentation/ —
tmp/cache/ and those data/output/ derivations are co-written by the same runs. The durable
data/output/ residents (input-derived deposits like data/output/memories, curations like
data/output/indexing/accepted.txt, the paid data/output/dashboard captures) have no
producer here and are never touched.

STDLIB-ONLY.

Usage:
    ./yoga cache sync              # run every producer
    ./yoga cache sync --dry-run    # print the producer commands; run nothing
"""
import argparse
import subprocess
import sys
from pathlib import Path

from cache_io import producers

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))  # src/main/ on the path
from argparse_help import enrich

REPO = Path(__file__).resolve().parents[3]


def main() -> int:
    ap = argparse.ArgumentParser(description='rebuild tmp/cache/ by running its declared producers')
    ap.add_argument('--dry-run', action='store_true')
    enrich(ap, 'cache', 'sync')
    args = ap.parse_args()

    cmds = producers()
    if args.dry_run:
        print(f'sync plan — {len(cmds)} producer run(s), in registry-row order:')
        for c in cmds:
            print(f'    → run: {c}')
        print('DONE — dry run: pass no flag to execute')
        return 0

    failures = []
    for c in cmds:
        print(f'── sync: {c} ────────────────────────────────')
        rc = subprocess.run(c, shell=True, cwd=REPO).returncode
        if rc != 0:
            failures.append((c, rc))
        print()

    if failures:
        print(f'DONE — {len(cmds)} producer(s) run, {len(failures)} FAILED:')
        for c, rc in failures:
            print(f'  FAIL: {c} (exit {rc})')
        return 1
    print(f'DONE — {len(cmds)} producer(s) run, tmp/cache/ rebuilt')
    return 0


if __name__ == '__main__':
    sys.exit(main())
