"""
generate_optional_check.py

Reads audit.json and emits a Python script that empirically checks whether
each optional field is ever absent in conversations.json.

audit.json format:
  Each entry has:
    def          - schema definition name (for labelling)
    data_path    - list of keys to navigate from each conversation object
                   to the collection of target objects. Special steps:
                     "content"  -> iterate array
                     "input"    -> access .input on each filtered parent
                   A filter applied at the penultimate array step selects
                   which objects to descend into.
    filter       - dict of {key: value} constraints applied at the first
                   array step that branches (i.e. "content")
    optional_fields - fields to check presence/absence of

Usage:
    python generate_optional_check.py audit.json > check_optional.py
    python check_optional.py conversations.json
"""
import sys, json

audit_path = sys.argv[1] if len(sys.argv) > 1 else 'audit.json'
audit = json.load(open(audit_path))

def build_expr(data_path, filter_dict):
    """
    Build a Python expression (string) that, given `data` (list of
    conversation dicts), yields the list of target objects described
    by data_path and filter_dict.

    data_path is walked step by step:
      - A step that is the first array step ("content") applies the filter.
      - "input" accesses the .input key of the filtered objects.
      - Nested array steps (second "content") iterate again.
      - A terminal key accesses that key on each object.
    """
    steps = data_path[:]

    # Start: data is a list of conversation dicts
    expr = 'data'

    # Step 1: chat_messages — always first, always an array
    assert steps[0] == 'chat_messages', f"Expected chat_messages, got {steps[0]}"
    steps.pop(0)
    expr = f'[_m for _c in ({expr}) for _m in _c.get("chat_messages", [])]'

    # Step 2: content — first array of content blocks, apply filter here
    assert steps[0] == 'content', f"Expected content, got {steps[0]}"
    steps.pop(0)
    filter_clauses = ' and '.join(
        f'_b.get({k!r}) == {v!r}' for k, v in filter_dict.items()
    )
    if filter_clauses:
        expr = f'[_b for _m in ({expr}) for _b in _m.get("content", []) if {filter_clauses}]'
    else:
        expr = f'[_b for _m in ({expr}) for _b in _m.get("content", [])]'

    # Remaining steps
    i = 0
    while i < len(steps):
        step = steps[i]
        if step == 'input':
            expr = f'[_b.get("input") for _b in ({expr}) if isinstance(_b, dict) and "input" in _b]'
        elif step == 'content':
            # nested array — iterate again, no filter
            expr = f'[_item for _b in ({expr}) for _item in (_b if isinstance(_b, list) else [])]'
        elif step == 'display_content':
            expr = f'[_b.get("display_content") for _b in ({expr}) if isinstance(_b, dict) and "display_content" in _b]'
        elif step == 'link':
            expr = f'[_b.get("link") for _b in ({expr}) if isinstance(_b, dict) and "link" in _b]'
        elif step == 'prompt_context_metadata':
            expr = f'[_b.get("prompt_context_metadata") for _b in ({expr}) if isinstance(_b, dict) and "prompt_context_metadata" in _b]'
        else:
            expr = f'[_b.get({step!r}) for _b in ({expr}) if isinstance(_b, dict) and {step!r} in _b]'
        i += 1

    return expr

# ── emit checker script ───────────────────────────────────────────────────────

print('"""')
print('check_optional.py  (generated by generate_optional_check.py)')
print('Usage: python check_optional.py conversations.json')
print('"""')
print('import sys, json')
print()
print('data = json.load(open(sys.argv[1] if len(sys.argv) > 1 else "conversations.json"))')
print()
print('def check(label, coll, field):')
print('    objs = [x for x in coll if isinstance(x, dict)]')
print('    total   = len(objs)')
print('    present = sum(1 for o in objs if field in o)')
print('    absent  = total - present')
print('    print(f"{label}: {present}/{total} present, {absent} absent")')
print()
print('# ── generated checks ────────────────────────────────────────────────────')

for entry in audit:
    def_name = entry['def']
    data_path = entry['data_path']
    filter_dict = entry.get('filter', {})
    optional_fields = entry.get('optional_fields', [])

    expr = build_expr(data_path, filter_dict)

    for field in optional_fields:
        label = f'{def_name}.{field}'
        print(f'\ncheck({label!r},')
        print(f'      {expr},')
        print(f'      {field!r})')