with open('/home/claude/paper0_v1.py', 'r') as f:
    content = f.read()

old = ('story.append(H2("2.3 What neg must therefore be — the intuitive choice"))\n'
'story.append(P(\n'
'    "Guided by the propositional status framing, we write down the intuitive "\n'
'    "antipodal operator on the three-value universe U = {-1, 0, 1}. "\n'
'    "We work in the full powerset P(U), ordered by inclusion. "\n'
'    "The universe has eight subsets; both operators are defined on all of them."))\n'
'story.append(P(\n'
'    "The complement operator not is the full set-theoretic complement. "\n'
'    "For neg, we ask: what is the natural opposite of each propositional "\n'
'    "category? The opposite of a true proposition is a false one; the "\n'
'    "opposite of a false proposition is a true one; the opposite of \'not "\n'
'    "even a statement\' is \'definitely one or the other\' — it forces "\n'
'    "propositional status. This gives, on singletons:"))\n'
'story.append(Math("neg({1}) = {-1},  neg({-1}) = {1},  neg({0}) = {-1,1}"))\n'
'story.append(P(\n'
'    "Extended to the full powerset by the natural antipodal structure, "\n'
'    "the complete definition is:"))\n'
'story.append(Math("neg: {-1,0,1}->∅,  {-1,0}->{1},  {-1,1}->{0},  {0,1}->{-1}"))\n'
'story.append(Math("     {-1}->{1},    {0}->{-1,1},  {1}->{-1},    ∅->{-1,0,1}"))\n'
'story.append(P(\n'
'    "This is our intuitive choice — written down from first principles, "\n'
'    "without any mention of Galois connections or adjunctions."))\n'
'story.append(P(\n'
'    "We now check its properties. The deflation neg(neg(A)) ⊆ A holds. "\n'
'    "Non-contradiction A ∩ neg(A) = ∅ holds. The third way exists: "\n'
'    "A ∪ neg(A) ⊊ U for singletons in {-1,1}. Not and neg differ "\n'
'    "at exactly the Boolean singletons: neg strips the third way from "\n'
'    "their complements, mapping to a definite opposite rather than "\n'
'    "admitting uncertainty as an output."))\n'
'story.append(P(\n'
'    "And then — the key discovery — our intuitive choice <i>happens to "\n'
'    "satisfy a Galois connection with not</i>: both A ⊆ not(neg(A)) and "\n'
'    "neg(not(A)) ⊆ A hold throughout the powerset. This was not imposed. "\n'
'    "It is a theorem about the model we wrote down for purely intuitive reasons."))\n'
'story.append(P(\n'
'    "The Galois connection was latent in the geometry of opposition. "\n'
'    "We found it by looking carefully at what opposition means, not by "\n'
'    "searching for adjunctions. This is the moment the programme opens up: "\n'
'    "Lawvere\'s observation that syntax and semantics are adjoint functors "\n'
'    "is not an abstract categorical theorem imposed from outside — it is "\n'
'    "what you find when you take seriously the difference between "\n'
'    "complement and opposition."))')

new = ('story.append(H2("2.3 The intuitive choice of neg"))\n'
'story.append(P(\n'
'    "We now simply write down the intuitive antipodal operator, guided solely "\n'
'    "by the propositional status framing. We work in the full powerset P(U), "\n'
'    "U = {-1,0,1}, ordered by inclusion. No further theory is assumed."))\n'
'story.append(P(\n'
'    "For neg, we ask only: what is the natural opposite of each propositional "\n'
'    "category? The opposite of a true proposition is a false one. The opposite "\n'
'    "of a false proposition is a true one. The opposite of \'not even a statement\' "\n'
'    "is \'definitely one or the other\' — negating the absence of propositional "\n'
'    "status forces a determinate value. This gives, on singletons:"))\n'
'story.append(Math("neg({1}) = {-1},  neg({-1}) = {1},  neg({0}) = {-1,1}"))\n'
'story.append(P(\n'
'    "Extended to the full powerset by the same antipodal logic:"))\n'
'story.append(Math("neg: {-1,0,1}->∅,  {-1,0}->{1},  {-1,1}->{0},  {0,1}->{-1}"))\n'
'story.append(Math("     {-1}->{1},    {0}->{-1,1},  {1}->{-1},    ∅->{-1,0,1}"))\n'
'story.append(P(\n'
'    "That is the complete definition. We wrote it down from intuition about "\n'
'    "propositional status. No adjunctions. No category theory. No Galois."))\n'
'story.append(H2("2.4 Checking properties"))\n'
'story.append(P(\n'
'    "We now verify what we have. Against the requirements established in "\n'
'    "Sections 2.1 and 2.2:"))\n'
'story.append(P(\n'
'    "Deflation neg(neg(A)) ⊆ A: verified throughout the powerset. ✓"))\n'
'story.append(P(\n'
'    "Non-contradiction A ∩ neg(A) = ∅: verified. Nothing is its own opposite. ✓"))\n'
'story.append(P(\n'
'    "Third way: A ∪ neg(A) ⊊ U for the Boolean singletons {-1} and {1}. "\n'
'    "neg({1}) = {-1} leaves {0} uncovered; neg({-1}) = {1} leaves {0} uncovered. "\n'
'    "The third way is genuinely present. ✓"))\n'
'story.append(P(\n'
'    "Not ≠ neg: they differ at exactly the Boolean singletons. "\n'
'    "not({-1}) = {0,1} while neg({-1}) = {1}; "\n'
'    "not({1}) = {-1,0} while neg({1}) = {-1}. "\n'
'    "neg strips the third way from the output of not on definite propositions — "\n'
'    "it maps to a determinate opposite, refusing to admit {0} as output. ✓"))\n'
'story.append(H2("2.5 The unexpected discovery"))\n'
'story.append(P(\n'
'    "Having verified the properties we asked for, we notice something we did "\n'
'    "not ask for. Checking the two inclusion conditions:"))\n'
'story.append(Math("A  ⊆  not(neg(A))  ?"))\n'
'story.append(Math("neg(not(A))  ⊆  A  ?"))\n'
'story.append(P(\n'
'    "Both hold throughout the powerset. This was not imposed — we never "\n'
'    "mentioned these conditions when writing down neg. They are theorems "\n'
'    "about the model we chose for purely intuitive reasons."))\n'
'story.append(P(\n'
'    "These two conditions are a <b>Galois connection</b>. We have stumbled "\n'
'    "upon — or rather, our intuition about opposition has delivered us directly "\n'
'    "to — one of the most fundamental structures in mathematics. Lawvere "\n'
'    "identified the Galois connection between syntax and semantics as the "\n'
'    "universal form of the gap between a formal system and its interpretations. "\n'
'    "We found it by asking what opposition means for propositions that are "\n'
'    "not even statements."))\n'
'story.append(P(\n'
'    "This is the moment the programme opens up. The Galois connection was "\n'
'    "latent in the geometry of opposition. It was not imported from category "\n'
'    "theory — it was discovered by looking carefully at what neg had to be. "\n'
'    "Everything that follows in this paper and its companions is a consequence "\n'
'    "of taking that discovery seriously."))')

if old in content:
    content = content.replace(old, new)
    print("Section 2.3-2.5 restructured correctly.")
else:
    print("Not found.")

with open('/home/claude/paper0_v1.py', 'w') as f:
    f.write(content)
print("Done.")