with open('/home/claude/paper0_v1.py', 'r') as f:
    content = f.read()

# Find and replace the entire Section 2 block
old = ('story.append(H1("2. Two Negations"))\n'
'story.append(P(\n'
'    "We operate not on truth values but on <b>propositions</b> — or more "\n'
'    "precisely, on the classification of sentences according to their "\n'
'    "propositional status. The three values are not degrees of truth but "\n'
'    "categories: 1 for true propositions, -1 for false propositions, and "\n'
'    "0 for sentences that are not yet — or not even — propositions "\n'
'    "susceptible to truth or falsity. The third way is not an unknown "\n'
'    "truth value; it is the <b>absence of propositional status</b>. A sentence "\n'
'    "in the third way has not failed to be true or false — it has not yet "\n'
'    "achieved the level of determinacy at which truth or falsity applies."))\n'
'story.append(H2("2.1 What not must be"))\n'
'story.append(P(\n'
'    "Any intuitive negation must be an involution. This is phenomenological, "\n'
'    "not axiomatic: if I say \'it is not the case that it is not raining,\' "\n'
'    "I mean it is raining. not(not(A)) = A is not a logical stipulation — "\n'
'    "it is the minimum requirement for the word \'not\' to mean what it "\n'
'    "ordinarily means. We take not to be the set-theoretic complement, "\n'
'    "which satisfies this involution property automatically, and whose "\n'
'    "order-reversing character is a theorem of the lattice structure, "\n'
'    "not an additional axiom."))\n'
'story.append(H2("2.2 What neg cannot be"))\n'
'story.append(P(\n'
'    "We want a second operator neg capturing opposition rather than "\n'
'    "complement. The first constraint is negative: <b>neg cannot be an "\n'
'    "involution</b>. This is a theorem, not a design choice."))\n'
'story.append(P(\n'
'    "<b>Theorem.</b> If neg is an involution and satisfies a Galois connection "\n'
'    "with not (itself an involution), then neg = not. The Boolean collapse "\n'
'    "is forced."))\n'
'story.append(P(\n'
'    "Proof sketch: the Galois conditions A ⊆ not(neg(A)) and neg(not(A)) ⊆ A, "\n'
'    "combined with both operators being involutions, force not ∘ neg = "\n'
'    "neg ∘ not, which by de Morgan\'s laws in the lattice setting forces "\n'
'    "neg = not. Therefore any neg genuinely distinct from not must fail "\n'
'    "to be an involution. The natural weakening — the weakest consistent "\n'
'    "alternative — is the deflation: neg(neg(A)) ⊆ A."))\n'
'story.append(P(\n'
'    "This is not a philosophical retreat. It is the theorem telling us "\n'
'    "what is possible. The deflation is not an axiom we impose out of "\n'
'    "caution — it is what we are forced to accept if we want neg and not "\n'
'    "to be genuinely distinct. The Boolean collapse is the only alternative, "\n'
'    "and the theorem proves it."))\n'
'story.append(H2("2.3 The intuitive choice of neg"))\n'
'story.append(P(\n'
'    "We now simply write down the intuitive antipodal operator, guided solely "\n'
'    "by the propositional status framing. We work in the full powerset P(U), "\n'
'    "U = {-1,0,1}, ordered by inclusion. No further theory is assumed."))\n'
'story.append(P(\n'
'    "For neg, we ask only: what is the natural opposite of each propositional "\n'
'    "category? The opposite of a true proposition is a false one. The opposite "\n'
'    "of a false proposition is a true one. The opposite of \'not even a statement\' "\n'
'    "is \'definitely one or the other\' — negating the absence of propositional "\n'
'    "status forces a determinate value. This gives, on singletons:"))\n'
'story.append(Math("neg({1}) = {-1},  neg({-1}) = {1},  neg({0}) = {-1,1}"))\n'
'story.append(P(\n'
'    "Extended to the full powerset by the same antipodal logic:"))\n'
'story.append(Math("neg: {-1,0,1}->∅,  {-1,0}->{1},  {-1,1}->{0},  {0,1}->{-1}"))\n'
'story.append(Math("     {-1}->{1},    {0}->{-1,1},  {1}->{-1},    ∅->{-1,0,1}"))\n'
'story.append(P(\n'
'    "That is the complete definition. We wrote it down from intuition about "\n'
'    "propositional status. No adjunctions. No category theory. No Galois."))\n'
'story.append(H2("2.4 Checking properties"))\n'
'story.append(P(\n'
'    "We now verify what we have. Against the requirements established in "\n'
'    "Sections 2.1 and 2.2:"))\n'
'story.append(P(\n'
'    "Deflation neg(neg(A)) ⊆ A: verified throughout the powerset. ✓"))\n'
'story.append(P(\n'
'    "Non-contradiction A ∩ neg(A) = ∅: verified. Nothing is its own opposite. ✓"))\n'
'story.append(P(\n'
'    "Third way: A ∪ neg(A) ⊊ U for the Boolean singletons {-1} and {1}. "\n'
'    "neg({1}) = {-1} leaves {0} uncovered; neg({-1}) = {1} leaves {0} uncovered. "\n'
'    "The third way is genuinely present. ✓"))\n'
'story.append(P(\n'
'    "Not ≠ neg: they differ at exactly the Boolean singletons. "\n'
'    "not({-1}) = {0,1} while neg({-1}) = {1}; "\n'
'    "not({1}) = {-1,0} while neg({1}) = {-1}. "\n'
'    "neg strips the third way from the output of not on definite propositions — "\n'
'    "it maps to a determinate opposite, refusing to admit {0} as output. ✓"))\n'
'story.append(H2("2.5 The unexpected discovery"))\n'
'story.append(P(\n'
'    "Having verified the properties we asked for, we notice something we did "\n'
'    "not ask for. Checking the two inclusion conditions:"))\n'
'story.append(Math("A  ⊆  not(neg(A))  ?"))\n'
'story.append(Math("neg(not(A))  ⊆  A  ?"))\n'
'story.append(P(\n'
'    "Both hold throughout the powerset. This was not imposed — we never "\n'
'    "mentioned these conditions when writing down neg. They are theorems "\n'
'    "about the model we chose for purely intuitive reasons."))\n'
'story.append(P(\n'
'    "These two conditions are a <b>Galois connection</b>. We have stumbled "\n'
'    "upon — or rather, our intuition about opposition has delivered us directly "\n'
'    "to — one of the most fundamental structures in mathematics. Lawvere "\n'
'    "identified the Galois connection between syntax and semantics as the "\n'
'    "universal form of the gap between a formal system and its interpretations. "\n'
'    "We found it by asking what opposition means for propositions that are "\n'
'    "not even statements."))\n'
'story.append(P(\n'
'    "This is the moment the programme opens up. The Galois connection was "\n'
'    "latent in the geometry of opposition. It was not imported from category "\n'
'    "theory — it was discovered by looking carefully at what neg had to be. "\n'
'    "Everything that follows in this paper and its companions is a consequence "\n'
'    "of taking that discovery seriously."))')

new = ('story.append(H1("2. Two Negations"))\n'
'story.append(P(\n'
'    "We operate not on truth values but on <b>propositions</b> — on the "\n'
'    "classification of sentences according to their propositional status. "\n'
'    "The three values are not degrees of truth but categories: 1 for true "\n'
'    "propositions, -1 for false propositions, and 0 for sentences that are "\n'
'    "not yet — or not even — propositions susceptible to truth or falsity. "\n'
'    "The third way is the <b>absence of propositional status</b>: a sentence "\n'
'    "that has not failed to be true or false, but has not yet achieved the "\n'
'    "level of determinacy at which truth or falsity applies."))\n'
'story.append(H2("2.1 not must be an involution"))\n'
'story.append(P(\n'
'    "Any intuitive negation must be an involution. This is phenomenological, "\n'
'    "not axiomatic. If I say \'it is not the case that it is not raining,\' I "\n'
'    "mean it is raining. not(not(A)) = A is the minimum requirement for the "\n'
'    "word \'not\' to mean what it ordinarily means — not a stipulation but a "\n'
'    "constraint from usage. We take not to be the set-theoretic complement "\n'
'    "on the full powerset P({-1,0,1}), which satisfies the involution property "\n'
'    "automatically. Its order-reversing character is a theorem of the lattice "\n'
'    "structure, not an additional axiom."))\n'
'story.append(H2("2.2 The third way must exist"))\n'
'story.append(P(\n'
'    "Separately and equally phenomenologically: there is obviously a third way. "\n'
'    "\'I don\'t know yet\', Gödel\'s undecidable propositions, Turing\'s "\n'
'    "non-terminating computations — all are instances of sentences that have "\n'
'    "not achieved propositional status. Any framework that forces every sentence "\n'
'    "to be true or false before that question has been settled is doing "\n'
'    "premature closure, not logic. The third way is not a gap to be filled "\n'
'    "but a category to be respected."))\n'
'story.append(H2("2.3 The intuitive choice of neg"))\n'
'story.append(P(\n'
'    "We now write down the intuitive antipodal operator, guided solely by "\n'
'    "the propositional status framing. No constraints are assumed beyond "\n'
'    "what intuition about opposition requires. We work in the full powerset "\n'
'    "P(U), U = {-1,0,1}, ordered by inclusion."))\n'
'story.append(P(\n'
'    "We ask only: what is the natural opposite of each propositional category? "\n'
'    "The opposite of a true proposition is a false one. The opposite of a "\n'
'    "false proposition is a true one. The opposite of \'not even a statement\' "\n'
'    "is \'definitely one or the other\' — negating the absence of propositional "\n'
'    "status forces a determinate value. On singletons:"))\n'
'story.append(Math("neg({1}) = {-1},   neg({-1}) = {1},   neg({0}) = {-1,1}"))\n'
'story.append(P("Extended to the full powerset by the same antipodal logic:"))\n'
'story.append(Math("neg: {-1,0,1}->∅,  {-1,0}->{1},  {-1,1}->{0},  {0,1}->{-1}"))\n'
'story.append(Math("     {-1}->{1},    {0}->{-1,1},  {1}->{-1},    ∅->{-1,0,1}"))\n'
'story.append(P(\n'
'    "That is the complete definition, written from intuition. "\n'
'    "No adjunctions. No category theory. No Galois."))\n'
'story.append(H2("2.4 The full table and what it shows"))\n'
'story.append(P(\n'
'    "We present both operators on all eight subsets of P(U), in the seven "\n'
'    "columns agreed. The table speaks for itself; we note what is visible."))\n'
'story.append(SP(4))\n'
'\n'
'# Full powerset table\n'
'from reportlab.platypus import Table, TableStyle\n'
'from reportlab.lib import colors as rl_colors\n'
'\n'
'not_map = {\n'
'    "{-1,0,1}": "∅",       "{-1,0}": "{1}",\n'
'    "{-1,1}":   "{0}",     "{0,1}":  "{-1}",\n'
'    "{-1}":     "{0,1}",   "{0}":    "{-1,1}",\n'
'    "{1}":      "{-1,0}",  "∅":      "{-1,0,1}",\n'
'}\n'
'neg_map = {\n'
'    "{-1,0,1}": "∅",       "{-1,0}": "{1}",\n'
'    "{-1,1}":   "{0}",     "{0,1}":  "{-1}",\n'
'    "{-1}":     "{1}",     "{0}":    "{-1,1}",\n'
'    "{1}":      "{-1}",    "∅":      "{-1,0,1}",\n'
'}\n'
'not_not_map = {k: not_map[not_map[k]] if not_map[k] in not_map else "?" for k in not_map}\n'
'\n'
'rows_order = ["{-1,0,1}","{-1,0}","{-1,1}","{0,1}","{-1}","{0}","{1}","∅"]\n'
'\n'
'def neg_neg(k):\n'
'    v = neg_map[k]\n'
'    return neg_map.get(v, "?")\n'
'\n'
'def not_neg(k):\n'
'    v = neg_map[k]\n'
'    return not_map.get(v, "?")\n'
'\n'
'def neg_not(k):\n'
'    v = not_map[k]\n'
'    return neg_map.get(v, "?")\n'
'\n'
'hdr = ["id", "not", "neg", "not(not)", "neg(neg)", "not(neg)", "neg(not)"]\n'
'tbl7_data = [hdr]\n'
'diff_rows = []\n'
'for i,k in enumerate(rows_order):\n'
'    nn = not_map.get(not_map.get(k,""),"?")\n'
'    gg = neg_neg(k)\n'
'    ng = not_neg(k)\n'
'    gn = neg_not(k)\n'
'    row = [k, not_map[k], neg_map[k], nn, gg, ng, gn]\n'
'    tbl7_data.append(row)\n'
'    if not_map[k] != neg_map[k]:\n'
'        diff_rows.append(i+1)\n'
'\n'
'cw7 = [1.6*cm, 1.5*cm, 1.5*cm, 1.5*cm, 1.5*cm, 1.5*cm, 1.5*cm]\n'
'style7 = TableStyle([\n'
'    ("FONTNAME",  (0,0), (-1,0),  "Times-Bold"),\n'
'    ("FONTNAME",  (0,1), (-1,-1), "Courier"),\n'
'    ("FONTSIZE",  (0,0), (-1,-1), 7.5),\n'
'    ("LEADING",   (0,0), (-1,-1), 10),\n'
'    ("ALIGN",     (0,0), (-1,-1), "CENTER"),\n'
'    ("VALIGN",    (0,0), (-1,-1), "MIDDLE"),\n'
'    ("TOPPADDING",(0,0), (-1,-1), 3),\n'
'    ("BOTTOMPADDING",(0,0),(-1,-1),3),\n'
'    ("LINEBELOW", (0,0), (-1,0),  0.6, rl_colors.black),\n'
'    ("LINEABOVE", (0,0), (-1,0),  0.6, rl_colors.black),\n'
'    ("LINEBELOW", (0,-1),(-1,-1), 0.6, rl_colors.black),\n'
'    ("BACKGROUND",(0,0), (-1,0),  rl_colors.HexColor("#f0f0f0")),\n'
'])\n'
'# Highlight rows where not != neg\n'
'for r in diff_rows:\n'
'    style7.add("BACKGROUND", (2,r), (2,r), rl_colors.HexColor("#fff0f0"))\n'
'    style7.add("TEXTCOLOR",  (2,r), (2,r), rl_colors.HexColor("#aa0000"))\n'
'\n'
'tbl7 = Table(tbl7_data, colWidths=cw7)\n'
'tbl7.setStyle(style7)\n'
'story.append(tbl7)\n'
'story.append(SP(6))\n'
'story.append(P(\n'
'    "We note what the table shows. not(not) = id throughout: not is an "\n'
'    "involution. neg(neg) ⊆ id throughout: neg happens to be a deflation. "\n'
'    "not and neg agree everywhere except at the Boolean singletons (red) — "\n'
'    "neg strips {0} from the output of not on definite propositions. "\n'
'    "The not(neg) and neg(not) columns are visible; we return to them shortly."))\n'
'story.append(SP(4))\n'
'story.append(H2("2.5 The opposites table"))\n'
'story.append(P(\n'
'    "The properties of the two operators are summarised by comparison:"))\n'
'story.append(SP(4))\n'
'\n'
'# Two-column opposites table\n'
'opp_data = [\n'
'    ["", "Complement", "Antipode"],\n'
'    ["Operation", "not", "neg"],\n'
'    ["Repetition", "not(not(A)) = A", "neg(neg(A)) ⊆ A"],\n'
'    ["Intersection", "A ∩ not(A) = ∅", "A ∩ neg(A) = ∅"],\n'
'    ["Union", "A ∪ not(A) = U", "A ∪ neg(A) ⊊ U"],\n'
']\n'
'cw_opp = [2.5*cm, 3.8*cm, 3.8*cm]\n'
'opp_style = TableStyle([\n'
'    ("FONTNAME",  (0,0), (-1,0),  "Times-Bold"),\n'
'    ("FONTNAME",  (0,1), (0,-1),  "Times-Italic"),\n'
'    ("FONTNAME",  (1,1), (2,1),   "Courier-Bold"),\n'
'    ("FONTNAME",  (1,2), (-1,-1), "Courier"),\n'
'    ("FONTSIZE",  (0,0), (-1,-1), 8.5),\n'
'    ("LEADING",   (0,0), (-1,-1), 12),\n'
'    ("ALIGN",     (0,0), (-1,-1), "CENTER"),\n'
'    ("VALIGN",    (0,0), (-1,-1), "MIDDLE"),\n'
'    ("TOPPADDING",(0,0), (-1,-1), 4),\n'
'    ("BOTTOMPADDING",(0,0),(-1,-1),4),\n'
'    ("LINEBELOW", (0,0), (-1,0),  0.6, rl_colors.black),\n'
'    ("LINEABOVE", (0,0), (-1,0),  0.6, rl_colors.black),\n'
'    ("LINEBELOW", (0,-1),(-1,-1), 0.6, rl_colors.black),\n'
'    ("LINEBEFORE",(1,0), (1,-1),  0.4, rl_colors.black),\n'
'    ("LINEBEFORE",(2,0), (2,-1),  0.4, rl_colors.black),\n'
'    ("BACKGROUND",(0,0), (-1,0),  rl_colors.HexColor("#f0f0f0")),\n'
'    ("BACKGROUND",(0,1), (0,-1),  rl_colors.HexColor("#f8f8f8")),\n'
'    ("TEXTCOLOR", (2,2), (2,2),   rl_colors.HexColor("#aa0000")),\n'
'    ("TEXTCOLOR", (2,4), (2,4),   rl_colors.HexColor("#aa0000")),\n'
'])\n'
'opp_tbl = Table(opp_data, colWidths=cw_opp)\n'
'opp_tbl.setStyle(opp_style)\n'
'story.append(opp_tbl)\n'
'story.append(SP(6))\n'
'story.append(P(\n'
'    "Reading across: intersection is identical — opposition is genuine in "\n'
'    "both logics. The two red entries mark the points of departure: deflation "\n'
'    "instead of involution, and strict inclusion instead of equality. These "\n'
'    "are not independent — we shall see shortly that they must change together."))\n'
'story.append(H2("2.6 The unexpected discovery"))\n'
'story.append(P(\n'
'    "Returning to the full table: we now look at the not(neg) and neg(not) "\n'
'    "columns, which we have not yet discussed. We notice something we did "\n'
'    "not ask for when writing down neg. In every row:"))\n'
'story.append(Math("id  ⊆  not(neg(id))"))\n'
'story.append(Math("neg(not(id))  ⊆  id"))\n'
'story.append(P(\n'
'    "Both inclusion conditions hold throughout the powerset. We never "\n'
'    "imposed them — they are theorems about the model we chose for "\n'
'    "purely intuitive reasons about propositional status."))\n'
'story.append(P(\n'
'    "These two conditions constitute a <b>Galois connection</b> between "\n'
'    "not and neg. We have not searched for one. Our intuition about "\n'
'    "what opposition means has delivered us directly to one of the most "\n'
'    "fundamental structures in mathematics."))\n'
'story.append(P(\n'
'    "Lawvere identified the Galois connection between syntax and semantics "\n'
'    "as the universal form of the gap between a formal system and its "\n'
'    "interpretations. We found it by asking what opposition means for "\n'
'    "sentences that are not even statements. The Galois connection was "\n'
'    "latent in the geometry of opposition all along."))\n'
'story.append(H2("2.7 The theorem neg cannot be an involution"))\n'
'story.append(P(\n'
'    "Now — and only now, having found the Galois connection — we can "\n'
'    "state and prove the theorem that retrospectively explains why our "\n'
'    "intuitive neg had to be a deflation."))\n'
'story.append(P(\n'
'    "<b>Theorem.</b> If neg satisfies a Galois connection with not (an involution) "\n'
'    "and neg is itself an involution, then neg = not. The Boolean collapse "\n'
'    "is forced."))\n'
'story.append(P(\n'
'    "Proof sketch: the Galois conditions combined with both operators being "\n'
'    "involutions force not ∘ neg = neg ∘ not. By de Morgan\'s laws in the "\n'
'    "lattice, this forces neg = not."))\n'
'story.append(P(\n'
'    "The deflation we found was not merely what our intuition happened to "\n'
'    "produce. It was the only consistent alternative to the Boolean collapse. "\n'
'    "Our intuition was right for the right reason: any genuinely distinct "\n'
'    "neg must be a deflation, and the theorem proves it. The two red entries "\n'
'    "in the opposites table must change together — they are the same fact "\n'
'    "seen from two angles."))')

if old in content:
    content = content.replace(old, new)
    print("Section 2 fully restructured.")
else:
    print("Not found — checking partial match...")
    idx = content.find('story.append(H1("2. Two Negations"))')
    print(f"Section 2 starts at index {idx}")
    idx2 = content.find('story.append(H1("3.')  )
    print(f"Section 3 starts at index {idx2}")
    print("Section 2 content:")
    print(repr(content[idx:idx+200]))

with open('/home/claude/paper0_v1.py', 'w') as f:
    f.write(content)
print("Done.")