with open('/home/claude/paper0_v1.py', 'r') as f:
    content = f.read()

old = ('story.append(NextPageTemplate(\'twocol\')); story.append(PageBreak())\n'
       '\n'
       '# ── SECTION 1 ─────────────────────────────────────────────────────────────────\n'
       'story.append(H1("1. The Misnomer and Its Consequences"))')

new = ('story.append(NextPageTemplate(\'twocol\')); story.append(PageBreak())\n'
       '\n'
       '# ── PREFACE ──────────────────────────────────────────────────────────────────\n'
       'story.append(H1("Preface: A Correction and Its Consequences"))\n'
       'story.append(P(\n'
       '    "This paper begins with a correction. The correction is small — a renaming, "\n'
       '    "a reframing, a refusal to accept a century-old description at face value. "\n'
       '    "But corrections of this kind are occasionally the most productive moves "\n'
       '    "in mathematics and science, because they remove an obstruction that has "\n'
       '    "been quietly taxing understanding across every domain that inherited the "\n'
       '    "confusion. What follows is an attempt to collect that tax refund."))\n'
       'story.append(P(\n'
       '    "The correction concerns negation. Classical logic has one negation. "\n'
       '    "The logic conventionally called intuitionistic has, in its standard "\n'
       '    "presentation, a weakened negation — one that fails to be an involution. "\n'
       '    "We propose instead to work with two negations, both genuine involutions, "\n'
       '    "connected by a Galois connection. The Boolean case — classical logic — "\n'
       '    "is recovered when the two coincide. The general case is richer, and "\n'
       '    "it is the general case that turns out to be the natural one."))\n'
       'story.append(P(\n'
       '    "The naming error — calling the general case \'intuitionistic\' and the "\n'
       '    "degenerate special case \'classical\' — has had consequences. It has made "\n'
       '    "the Boolean collapse look like the natural default and the escape from it "\n'
       '    "look like a philosophical commitment. It has obscured the fact that three "\n'
       '    "of the deepest results of twentieth-century logic and computation — "\n'
       '    "Gödel\'s incompleteness, Turing\'s undecidability, and the simple "\n'
       '    "observation that any honest finite agent sometimes says \'I don\'t know "\n'
       '    "yet\' — all point toward the same conclusion: the Boolean collapse is "\n'
       '    "the special case, not the general condition. And it has hidden the fact "\n'
       '    "that the genuinely constructive mode of reasoning — the one that actually "\n'
       '    "builds something durable — requires the full two-negation geometry, not "\n'
       '    "its Boolean shadow."))\n'
       'story.append(P(\n'
       '    "This paper makes the correction precise and traces its immediate "\n'
       '    "consequences in logic, algebra, and cultural reasoning. But the correction "\n'
       '    "has a longer reach. The companion papers in this series follow it into "\n'
       '    "geometry, physics, thermodynamics, and topology, finding in each domain "\n'
       '    "new clarity that was latent in the structure all along, obscured by the "\n'
       '    "inherited confusion. The programme is not five papers on related topics. "\n'
       '    "It is one correction and its consequences."))\n'
       'story.append(P(\n'
       '    "<b>Paper 0</b> (this paper) diagnoses the error, corrects it, and shows "\n'
       '    "that the Boolean collapse is not constructive — in mathematics, in logic, "\n'
       '    "or in the social and political domains where its consequences are most "\n'
       '    "visible. <b>Paper 1</b> follows the correction into the foundations of "\n'
       '    "geometry and physics, deriving relativistic uncertainty and the structure "\n'
       '    "of measurement from the causal skeleton alone. <b>Paper 2</b> follows it "\n'
       '    "into thermodynamics, finding that temperature is a primitive scalar field "\n'
       '    "conjugate to curvature, and that the Unruh effect and the Hawking "\n'
       '    "temperature are geometric results requiring no quantum field theory. "\n'
       '    "<b>Paper 3</b> follows it into topological dynamics, connecting vorticity, "\n'
       '    "helicity, and curvature rotons in a unified non-ecological framework. "\n'
       '    "<b>Paper 4</b> closes the loop with Noether\'s theorem: every symmetry "\n'
       '    "generates a conserved quantity; every coupling generates an uncertainty "\n'
       '    "relation; and the action, read as the dissipative cost of a path, is "\n'
       '    "the receipt for the trajectory."))\n'
       'story.append(P(\n'
       '    "The reader who finds the logical argument of this paper compelling is "\n'
       '    "invited to follow it wherever it leads. The landscape is larger than it "\n'
       '    "appears from the entrance, and the view from the other side of the "\n'
       '    "correction is considerably clearer."))\n'
       'story.append(SP(6))\n'
       'story.append(Rule())\n'
       'story.append(SP(4))\n'
       '\n'
       '# ── SECTION 1 ─────────────────────────────────────────────────────────────────\n'
       'story.append(H1("1. The Misnomer and Its Consequences"))')

if old in content:
    content = content.replace(old, new)
    with open('/home/claude/paper0_v1.py', 'w') as f:
        f.write(content)
    print("Done.")
else:
    print("Not found.")
    idx = content.find("# ── SECTION 1")
    print(repr(content[idx-100:idx+50]))