with open('/home/claude/paper0_v1.py', 'r') as f:
    content = f.read()

# Replace Section 2 opening with the correct phenomenological/logical order
old = ('story.append(H1("2. Two Negations"))\n'
       'story.append(P(\n'
       '    "We operate not on truth values but on <b>propositions</b> — or more "\n'
       '    "precisely, on the classification of sentences according to their "\n'
       '    "propositional status. The three values are not degrees of truth but "\n'
       '    "categories: 1 for true propositions, -1 for false propositions, and "\n'
       '    "0 for sentences that are not yet — or not even — propositions "\n'
       '    "susceptible to truth or falsity. The third way is not an unknown "\n'
       '    "truth value; it is the <b>absence of propositional status</b>. A sentence "\n'
       '    "in the third way has not failed to be true or false — it has not yet "\n'
       '    "achieved the level of determinacy at which truth or falsity applies."))\n'
       'story.append(P(\n'
       '    "This reframing is not merely philosophical. It explains directly why "\n'
       '    "the order-reversing property holds within each category but not across "\n'
       '    "the category boundary. The sets {0} and {-1,1} are not comparable by "\n'
       '    "inclusion because they inhabit different layers of the logical hierarchy: "\n'
       '    "one classifies propositional status, the other classifies truth value. "\n'
       '    "The order-reversing failure of neg is not a defect but a diagnostic — "\n'
       '    "it marks precisely where the category boundary lies."))\n'
       'story.append(P(\n'
       '    "We work in the powerset P({-1,0,1}), ordered by inclusion. "\n'
       '    "The universe is U = {-1,0,1}. Both not and neg are functions on "\n'
       '    "the full powerset — we list their values on singletons for "\n'
       '    "illustration, but the operators are defined on all eight subsets."))')

new = ('story.append(H1("2. Two Negations"))\n'
       'story.append(P(\n'
       '    "We operate not on truth values but on <b>propositions</b> — or more "\n'
       '    "precisely, on the classification of sentences according to their "\n'
       '    "propositional status. The three values are not degrees of truth but "\n'
       '    "categories: 1 for true propositions, -1 for false propositions, and "\n'
       '    "0 for sentences that are not yet — or not even — propositions "\n'
       '    "susceptible to truth or falsity. The third way is not an unknown "\n'
       '    "truth value; it is the <b>absence of propositional status</b>. A sentence "\n'
       '    "in the third way has not failed to be true or false — it has not yet "\n'
       '    "achieved the level of determinacy at which truth or falsity applies."))\n'
       'story.append(H2("2.1 What not must be"))\n'
       'story.append(P(\n'
       '    "Any intuitive negation must be an involution. This is phenomenological, "\n'
       '    "not axiomatic: if I say \'it is not the case that it is not raining,\' "\n'
       '    "I mean it is raining. not(not(A)) = A is not a logical stipulation — "\n'
       '    "it is the minimum requirement for the word \'not\' to mean what it "\n'
       '    "ordinarily means. We take not to be the set-theoretic complement, "\n'
       '    "which satisfies this involution property automatically, and whose "\n'
       '    "order-reversing character is a theorem of the lattice structure, "\n'
       '    "not an additional axiom."))\n'
       'story.append(H2("2.2 What neg cannot be"))\n'
       'story.append(P(\n'
       '    "We want a second operator neg capturing opposition rather than "\n'
       '    "complement. The first constraint is negative: <b>neg cannot be an "\n'
       '    "involution</b>. This is a theorem, not a design choice."))\n'
       'story.append(P(\n'
       '    "<b>Theorem.</b> If neg is an involution and satisfies a Galois connection "\n'
       '    "with not (itself an involution), then neg = not. The Boolean collapse "\n'
       '    "is forced."))\n'
       'story.append(P(\n'
       '    "Proof sketch: the Galois conditions A ⊆ not(neg(A)) and neg(not(A)) ⊆ A, "\n'
       '    "combined with both operators being involutions, force not ∘ neg = "\n'
       '    "neg ∘ not, which by de Morgan\'s laws in the lattice setting forces "\n'
       '    "neg = not. Therefore any neg genuinely distinct from not must fail "\n'
       '    "to be an involution. The natural weakening — the weakest consistent "\n'
       '    "alternative — is the deflation: neg(neg(A)) ⊆ A."))\n'
       'story.append(P(\n'
       '    "This is not a philosophical retreat. It is the theorem telling us "\n'
       '    "what is possible. The deflation is not an axiom we impose out of "\n'
       '    "caution — it is what we are forced to accept if we want neg and not "\n'
       '    "to be genuinely distinct. The Boolean collapse is the only alternative, "\n'
       '    "and the theorem proves it."))\n'
       'story.append(H2("2.3 What neg must therefore be — the intuitive choice"))\n'
       'story.append(P(\n'
       '    "Guided by the propositional status framing, we write down the intuitive "\n'
       '    "antipodal operator on the three-value universe U = {-1, 0, 1}. "\n'
       '    "We work in the full powerset P(U), ordered by inclusion. "\n'
       '    "The universe has eight subsets; both operators are defined on all of them."))\n'
       'story.append(P(\n'
       '    "The complement operator not is the full set-theoretic complement. "\n'
       '    "For neg, we ask: what is the natural opposite of each propositional "\n'
       '    "category? The opposite of a true proposition is a false one; the "\n'
       '    "opposite of a false proposition is a true one; the opposite of \'not "\n'
       '    "even a statement\' is \'definitely one or the other\' — it forces "\n'
       '    "propositional status. This gives, on singletons:"))\n'
       'story.append(Math("neg({1}) = {-1},  neg({-1}) = {1},  neg({0}) = {-1,1}"))\n'
       'story.append(P(\n'
       '    "Extended to the full powerset by the natural antipodal structure, "\n'
       '    "the complete definition is:"))\n'
       'story.append(Math("neg: {-1,0,1}->∅,  {-1,0}->{1},  {-1,1}->{0},  {0,1}->{-1}"))\n'
       'story.append(Math("     {-1}->{1},    {0}->{-1,1},  {1}->{-1},    ∅->{-1,0,1}"))\n'
       'story.append(P(\n'
       '    "This is our intuitive choice — written down from first principles, "\n'
       '    "without any mention of Galois connections or adjunctions."))\n'
       'story.append(P(\n'
       '    "We now check its properties. The deflation neg(neg(A)) ⊆ A holds. "\n'
       '    "Non-contradiction A ∩ neg(A) = ∅ holds. The third way exists: "\n'
       '    "A ∪ neg(A) ⊊ U for singletons in {-1,1}. Not and neg differ "\n'
       '    "at exactly the Boolean singletons: neg strips the third way from "\n'
       '    "their complements, mapping to a definite opposite rather than "\n'
       '    "admitting uncertainty as an output."))\n'
       'story.append(P(\n'
       '    "And then — the key discovery — our intuitive choice <i>happens to "\n'
       '    "satisfy a Galois connection with not</i>: both A ⊆ not(neg(A)) and "\n'
       '    "neg(not(A)) ⊆ A hold throughout the powerset. This was not imposed. "\n'
       '    "It is a theorem about the model we wrote down for purely intuitive reasons."))\n'
       'story.append(P(\n'
       '    "The Galois connection was latent in the geometry of opposition. "\n'
       '    "We found it by looking carefully at what opposition means, not by "\n'
       '    "searching for adjunctions. This is the moment the programme opens up: "\n'
       '    "Lawvere\'s observation that syntax and semantics are adjoint functors "\n'
       '    "is not an abstract categorical theorem imposed from outside — it is "\n'
       '    "what you find when you take seriously the difference between "\n'
       '    "complement and opposition."))')

if old in content:
    content = content.replace(old, new)
    print("Section 2 restructured.")
else:
    print("Not found.")
    idx = content.find('"We operate not on truth values')
    print(repr(content[idx-50:idx+100]))

with open('/home/claude/paper0_v1.py', 'w') as f:
    f.write(content)
print("Done.")