#!/usr/bin/env python3
"""
gen_refs.py — the code-side manifest of the input/ + output/markdown restructure.

Scans every committed file for references to the OLD data layout and emits
refs.csv (file, line, kind, old_form, proposal, text): the reviewable record of
what the code sweep must touch. Kinds:

  mechanical — an unambiguous old→new string swap
  decide     — a site needing judgment before any swap:
                 * input/browser-captures/claude BIFURCATES (browser-API json
                   vs browser-DOM md) — each call site must choose
                 * the bare browser-captures root disappears (boundary moves)
                 * prose brace-forms and flag names
  stay-cache — looks like a hit but lives in cache/ (pipeline-keyed, unchanged)

Deliberately NOT emitted: bare pipeline names (browser-captures, chat-exports,
code-agents as pipeline ids, src/main/<pipeline>/ code locations, cache/ roots,
rsc/cache_io.csv keys) — the pipeline vocabulary is untouched by design.
"""
import csv, re, subprocess
from pathlib import Path

import argparse
_ap = argparse.ArgumentParser()
_ap.add_argument('--from', dest='repo', required=True,
                 help='the OLD-layout checkout whose committed files are scanned')
REPO = Path(_ap.parse_args().repo).resolve()
OUT = Path.cwd() / 'refs.csv'

# (name, regex, proposal, kind) — first match wins per (pattern, line)
P = [
    ('in-bc-claude', r'input/browser-captures/claude',
     'BIFURCATES: input/claude/chat/browser-API (json) | input/claude/chat/browser-DOM (scrape md) — choose per site', 'decide'),
    ('in-bc-gemini', r'input/browser-captures/gemini',
     'input/gemini/chat/browser-DOM', 'mechanical'),
    ('in-bc-root', r'input/browser-captures(?!/(?:claude|gemini))',
     'root disappears — boundary becomes input/{claude,gemini}; choose per site', 'decide'),
    ('in-chat-exports', r'input/chat-exports',
     'input/claude/chat/bulk-export', 'mechanical'),
    ('in-code-agents', r'input/code-agents',
     'input/claude/code/machine-transport', 'mechanical'),
    ('in-code-projects', r'input/code-projects',
     'input/claude-code-projects', 'mechanical'),
    ('md-claude-leaf', r'output/markdown/claude/(conversations|memories|summaries)',
     'output/markdown/claude/chat/<leaf>', 'mechanical'),
    ('md-code', r'output/markdown/code\b',
     'output/markdown/claude/code', 'mechanical'),
    ('md-gemini-leaf', r'output/markdown/gemini/conversations',
     'output/markdown/gemini/chat/conversations', 'mechanical'),
    ('md-brace-prose', r'output/markdown/\{[^}]*\}',
     'prose brace-form — rewrite by hand', 'decide'),
    # python join forms
    ('py-bc-claude', r"'browser-captures'\s*/\s*'claude'",
     "BIFURCATES (join form): 'claude'/'chat'/'browser-API' | .../'browser-DOM'", 'decide'),
    ('py-bc-gemini', r"'browser-captures'\s*/\s*'gemini'",
     "'gemini' / 'chat' / 'browser-DOM'", 'mechanical'),
    ('py-bc-root', r"'input'\s*/\s*'browser-captures'(?!\s*/\s*'(?:claude|gemini)')",
     'root disappears (join form) — often an agent-varying default; choose per site', 'decide'),
    ('py-chat-exports', r"'input'\s*/\s*'chat-exports'",
     "'input' / 'claude' / 'chat' / 'bulk-export'", 'mechanical'),
    ('py-code-agents', r"'input'\s*/\s*'code-agents'",
     "'input' / 'claude' / 'code' / 'machine-transport'", 'mechanical'),
    ('py-code-projects', r"'input'\s*/\s*'code-projects'",
     "'input' / 'claude-code-projects'", 'mechanical'),
    ('py-md-claude-leaf', r"'markdown'\s*/\s*'claude'\s*/\s*'(conversations|memories|summaries)'",
     "insert 'chat': 'markdown'/'claude'/'chat'/<leaf>", 'mechanical'),
    ('py-md-code', r"'markdown'\s*/\s*'code'",
     "'markdown' / 'claude' / 'code'", 'mechanical'),
    ('py-md-gemini', r"'markdown'\s*/\s*'gemini'",
     "insert 'chat' before the leaf", 'mechanical'),
    # tier-named CLI flags whose referent bifurcates or renames
    ('flag-browser-captures', r'--browser-captures\b',
     'flag name: referent bifurcates — rename or repoint; decide', 'decide'),
    ('flag-captures', r'--captures\b',
     'flag name: which mechanism does it mean now? decide', 'decide'),
    ('flag-chat-exports', r'--chat-exports\b',
     'flag name: mechanism vocabulary suggests --bulk-export; decide', 'decide'),
]

DERIVED = {'src/test/xref.csv', 'src/test/pre_commit.log'}  # regenerated by the gate
files = [f for f in subprocess.run(['git', 'ls-files'], cwd=REPO, capture_output=True,
                                   text=True).stdout.split() if f not in DERIVED]
rows = []
for rel in files:
    p = REPO / rel
    try:
        text = p.read_text()
    except (UnicodeDecodeError, IsADirectoryError):
        continue
    for lineno, line in enumerate(text.splitlines(), 1):
        for name, rx, proposal, kind in P:
            if re.search(rx, line):
                k = kind
                if name.startswith('py-') and 'cache' in line and 'input' not in line \
                        and 'markdown' not in name:
                    k = 'stay-cache'
                rows.append((rel, lineno, k, name, proposal, line.strip()[:160]))

with open(OUT, 'w', newline='') as fh:
    w = csv.writer(fh)
    w.writerow(['file', 'line', 'kind', 'pattern', 'proposal', 'text'])
    w.writerows(rows)

from collections import Counter
by_kind = Counter(r[2] for r in rows)
by_file = Counter(r[0] for r in rows)
print(f'{len(rows)} reference(s) across {len(by_file)} file(s)')
print('by kind:', dict(by_kind))
print('\ntop files:')
for f, n in by_file.most_common(12):
    print(f'  {n:4} {f}')
print('\ndecide sites by pattern:')
for pat, n in Counter(r[3] for r in rows if r[2] == 'decide').most_common():
    print(f'  {n:4} {pat}')
