"""
check_optional.py  (generated by generate_optional_check.py)
Usage: python check_optional.py conversations.json
"""
import sys, json

data = json.load(open(sys.argv[1] if len(sys.argv) > 1 else "conversations.json"))

def check(label, coll, field):
    objs = [x for x in coll if isinstance(x, dict)]
    total   = len(objs)
    present = sum(1 for o in objs if field in o)
    absent  = total - present
    print(f"{label}: {present}/{total} present, {absent} absent")

# ── generated checks ────────────────────────────────────────────────────

check('ToolUseBlockBase.mcp_server_url',
      [_b for _m in ([_m for _c in (data) for _m in _c.get("chat_messages", [])]) for _b in _m.get("content", []) if _b.get('type') == 'tool_use'],
      'mcp_server_url')

check('ToolResultBlockBase.mcp_server_url',
      [_b for _m in ([_m for _c in (data) for _m in _c.get("chat_messages", [])]) for _b in _m.get("content", []) if _b.get('type') == 'tool_result'],
      'mcp_server_url')

check('ToolInputBash[bash_tool].description',
      [_b.get("input") for _b in ([_b for _m in ([_m for _c in (data) for _m in _c.get("chat_messages", [])]) for _b in _m.get("content", []) if _b.get('type') == 'tool_use' and _b.get('name') == 'bash_tool']) if isinstance(_b, dict) and "input" in _b],
      'description')

check('ToolInputBash[memory_user_edits].description',
      [_b.get("input") for _b in ([_b for _m in ([_m for _c in (data) for _m in _c.get("chat_messages", [])]) for _b in _m.get("content", []) if _b.get('type') == 'tool_use' and _b.get('name') == 'memory_user_edits']) if isinstance(_b, dict) and "input" in _b],
      'description')

check('ToolInputStrReplace.description',
      [_b.get("input") for _b in ([_b for _m in ([_m for _c in (data) for _m in _c.get("chat_messages", [])]) for _b in _m.get("content", []) if _b.get('type') == 'tool_use' and _b.get('name') == 'str_replace']) if isinstance(_b, dict) and "input" in _b],
      'description')

check('ToolInputStrReplace.path',
      [_b.get("input") for _b in ([_b for _m in ([_m for _c in (data) for _m in _c.get("chat_messages", [])]) for _b in _m.get("content", []) if _b.get('type') == 'tool_use' and _b.get('name') == 'str_replace']) if isinstance(_b, dict) and "input" in _b],
      'path')

check('ToolInputView.description',
      [_b.get("input") for _b in ([_b for _m in ([_m for _c in (data) for _m in _c.get("chat_messages", [])]) for _b in _m.get("content", []) if _b.get('type') == 'tool_use' and _b.get('name') == 'view']) if isinstance(_b, dict) and "input" in _b],
      'description')

check('ToolInputView.view_range',
      [_b.get("input") for _b in ([_b for _m in ([_m for _c in (data) for _m in _c.get("chat_messages", [])]) for _b in _m.get("content", []) if _b.get('type') == 'tool_use' and _b.get('name') == 'view']) if isinstance(_b, dict) and "input" in _b],
      'view_range')

check('ToolInputVisualizer.i_have_seen_read_me',
      [_b.get("input") for _b in ([_b for _m in ([_m for _c in (data) for _m in _c.get("chat_messages", [])]) for _b in _m.get("content", []) if _b.get('type') == 'tool_use' and _b.get('name') == 'visualize:show_widget']) if isinstance(_b, dict) and "input" in _b],
      'i_have_seen_read_me')

check('ToolInputWebFetch.html_extraction_method',
      [_b.get("input") for _b in ([_b for _m in ([_m for _c in (data) for _m in _c.get("chat_messages", [])]) for _b in _m.get("content", []) if _b.get('type') == 'tool_use' and _b.get('name') == 'web_fetch']) if isinstance(_b, dict) and "input" in _b],
      'html_extraction_method')

check('ToolInputWebFetch.web_fetch_pdf_extract_text',
      [_b.get("input") for _b in ([_b for _m in ([_m for _c in (data) for _m in _c.get("chat_messages", [])]) for _b in _m.get("content", []) if _b.get('type') == 'tool_use' and _b.get('name') == 'web_fetch']) if isinstance(_b, dict) and "input" in _b],
      'web_fetch_pdf_extract_text')

check('PromptContextMetadataSearch.age',
      [_b.get("prompt_context_metadata") for _b in ([_item for _b in ([_b for _m in ([_m for _c in (data) for _m in _c.get("chat_messages", [])]) for _b in _m.get("content", []) if _b.get('type') == 'tool_result']) for _item in (_b.get("content") or []) if _item.get('type') == 'knowledge']) if isinstance(_b, dict) and "prompt_context_metadata" in _b],
      'age')

check('RichLink.resource_type',
      [_b.get("link") for _b in ([_b.get("display_content") for _b in ([_b for _m in ([_m for _c in (data) for _m in _c.get("chat_messages", [])]) for _b in _m.get("content", []) if _b.get('type') == 'tool_result']) if isinstance(_b, dict) and "display_content" in _b]) if isinstance(_b, dict) and "link" in _b],
      'resource_type')

check('RichLink.subtitles',
      [_b.get("link") for _b in ([_b.get("display_content") for _b in ([_b for _m in ([_m for _c in (data) for _m in _c.get("chat_messages", [])]) for _b in _m.get("content", []) if _b.get('type') == 'tool_result']) if isinstance(_b, dict) and "display_content" in _b]) if isinstance(_b, dict) and "link" in _b],
      'subtitles')
