#!/usr/bin/env python
"""
sync.py — rebuild tmp/cache/ by running its producers.

tmp/cache/ is the workshop — rebuildable derivations. Its producer commands are
DECLARED in rsc/cache_io.csv (written_by); sync runs every row's producers,
in registry-row order (no dedup — the row is the unit of the claim). Paired with clean, this is the reproduction the tmp/cache/
contract promises: `yoga cache clean --apply && yoga cache sync` gives a fresh tmp/cache/ from
data/input/ + data/output/ alone. The one fetched store, ext/lib/serve_markdown's render
libraries (KaTeX + marked), lives outside tmp/cache/ and outside this registry:
`yoga server ensure-assets` rebuilds it, best-effort (it warns and exits clean if
offline; serve re-fetches at startup), so an offline sync still rebuilds every
subtree this registry names.

Producers are FREE and — but for that render-asset fetch — LOCAL. The paid `yoga
dashboard capture` is not among them (tmp/cache/dashboard is regenerated by `present`,
which reads the already-captured data/output/dashboard). sync never spends money. It
DOES co-write data/output/: the pipeline producers project markdown there, and
`site render` lands the corpus page in data/output/site/ —
tmp/cache/ and those data/output/ derivations are co-written by the same runs. The durable
data/output/ residents (input-derived deposits like data/output/memories, curations like
data/output/indexing/accepted.txt, the paid data/output/dashboard captures) have no
producer here and are never touched.

STDLIB-ONLY.

Usage:
    yoga cache sync              # run every producer
    yoga cache sync --dry-run    # print the producer commands; run nothing
"""
import subprocess
import sys
from pathlib import Path

from cache_io import producers

SELF = 'src/main/cli/cache/sync.py'
_file = Path(__file__).resolve()
_root = [p for p in _file.parents if p / SELF == _file]
assert _root, f'{_file} is not at its declared address {SELF}'
REPO_ROOT = _root[0]
sys.path.insert(0, str(REPO_ROOT / 'src'))  # src/ — modules both tiers import
from declared_parser import verb_parser

REPO = REPO_ROOT


def main() -> int:
    args = verb_parser('cache', 'sync').parse_args()  # generated from the declaration (#476)

    # The registry stores canonical NAMES ('yoga model sync' — one referent, one
    # name, G14), and every printed line speaks the name too: './yoga' is no more
    # runnable for a reader than bare 'yoga' — one presumes cwd, the other PATH
    # (user ruling, PR #109). The './' spelling exists at exactly ONE point, the
    # exec boundary below, where it is valid because the same call pins cwd=REPO.
    def executable(c: str) -> str:
        return f'./{c}' if c.startswith('yoga ') else c

    cmds = producers()
    if args.dry_run:
        print(f'sync plan — {len(cmds)} producer run(s), in registry-row order:')
        for c in cmds:
            print(f'    → run: {c}')
        print('DONE — dry run: pass no flag to execute')
        return 0

    failures = []
    for c in cmds:
        print(f'── sync: {c} ────────────────────────────────')
        rc = subprocess.run(executable(c), shell=True, cwd=REPO).returncode
        if rc != 0:
            failures.append((c, rc))
        print()

    if failures:
        print(f'DONE — {len(cmds)} producer(s) run, {len(failures)} FAILED:')
        for c, rc in failures:
            print(f'  FAIL: {c} (exit {rc})')
        return 1
    print(f'DONE — {len(cmds)} producer(s) run, tmp/cache/ rebuilt')
    return 0


if __name__ == '__main__':
    sys.exit(main())
